// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: grpc/vendor.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeRequest) Reset() {
	*x = VolumeRequest{}
	mi := &file_grpc_vendor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRequest) ProtoMessage() {}

func (x *VolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_vendor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRequest.ProtoReflect.Descriptor instead.
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_vendor_proto_rawDescGZIP(), []int{0}
}

func (x *VolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type VolumeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeReply) Reset() {
	*x = VolumeReply{}
	mi := &file_grpc_vendor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeReply) ProtoMessage() {}

func (x *VolumeReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_vendor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeReply.ProtoReflect.Descriptor instead.
func (*VolumeReply) Descriptor() ([]byte, []int) {
	return file_grpc_vendor_proto_rawDescGZIP(), []int{1}
}

func (x *VolumeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VolumeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ServerIp      string                 `protobuf:"bytes,3,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeInfo) Reset() {
	*x = VolumeInfo{}
	mi := &file_grpc_vendor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeInfo) ProtoMessage() {}

func (x *VolumeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_vendor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeInfo.ProtoReflect.Descriptor instead.
func (*VolumeInfo) Descriptor() ([]byte, []int) {
	return file_grpc_vendor_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VolumeInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VolumeInfo) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

var File_grpc_vendor_proto protoreflect.FileDescriptor

const file_grpc_vendor_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/vendor.proto\x12\flocalcluster\"7\n" +
	"\rVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"'\n" +
	"\vVolumeReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"U\n" +
	"\n" +
	"VolumeInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tserver_ip\x18\x03 \x01(\tR\bserverIp2\xe5\x01\n" +
	"\vLocalVendor\x12F\n" +
	"\fCreateVolume\x12\x1b.localcluster.VolumeRequest\x1a\x19.localcluster.VolumeReply\x12F\n" +
	"\rGetVolumeInfo\x12\x1b.localcluster.VolumeRequest\x1a\x18.localcluster.VolumeInfo\x12F\n" +
	"\fDeleteVolume\x12\x1b.localcluster.VolumeRequest\x1a\x19.localcluster.VolumeReplyB\x0fZ\rsimplebs/grpcb\x06proto3"

var (
	file_grpc_vendor_proto_rawDescOnce sync.Once
	file_grpc_vendor_proto_rawDescData []byte
)

func file_grpc_vendor_proto_rawDescGZIP() []byte {
	file_grpc_vendor_proto_rawDescOnce.Do(func() {
		file_grpc_vendor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_vendor_proto_rawDesc), len(file_grpc_vendor_proto_rawDesc)))
	})
	return file_grpc_vendor_proto_rawDescData
}

var file_grpc_vendor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_vendor_proto_goTypes = []any{
	(*VolumeRequest)(nil), // 0: localcluster.VolumeRequest
	(*VolumeReply)(nil),   // 1: localcluster.VolumeReply
	(*VolumeInfo)(nil),    // 2: localcluster.VolumeInfo
}
var file_grpc_vendor_proto_depIdxs = []int32{
	0, // 0: localcluster.LocalVendor.CreateVolume:input_type -> localcluster.VolumeRequest
	0, // 1: localcluster.LocalVendor.GetVolumeInfo:input_type -> localcluster.VolumeRequest
	0, // 2: localcluster.LocalVendor.DeleteVolume:input_type -> localcluster.VolumeRequest
	1, // 3: localcluster.LocalVendor.CreateVolume:output_type -> localcluster.VolumeReply
	2, // 4: localcluster.LocalVendor.GetVolumeInfo:output_type -> localcluster.VolumeInfo
	1, // 5: localcluster.LocalVendor.DeleteVolume:output_type -> localcluster.VolumeReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_vendor_proto_init() }
func file_grpc_vendor_proto_init() {
	if File_grpc_vendor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_vendor_proto_rawDesc), len(file_grpc_vendor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_vendor_proto_goTypes,
		DependencyIndexes: file_grpc_vendor_proto_depIdxs,
		MessageInfos:      file_grpc_vendor_proto_msgTypes,
	}.Build()
	File_grpc_vendor_proto = out.File
	file_grpc_vendor_proto_goTypes = nil
	file_grpc_vendor_proto_depIdxs = nil
}
